[package]
name = "trail-config"
version = "0.1.5"
edition = "2018"
authors = ["Robert Lampreht <robert.lampreht@gmail.com>"]
description = "Simple library to help with reading (and formatting) values from config files"
readme = "README.md"
keywords = ["config", "conf", "cfg", "yaml", "trail"]
license = "MIT"
repository = "https://github.com/rbt-dev/trail-config.git"

[lib]
name = "trail_config"
path = "src/lib.rs"

[dependencies]
serde_yaml = "0.9.33"
strfmt = "0.2.4"
